### ISSUE TITLE
Issues with user during clone operation

### ISSUE THREAD

**Issue by wturnerharris** [ucb-ist-drupal/SiteClone#14]
> [2016-11-11 16:02:40] [error] Site creation aborted. User is not a member of the selected organization.
> [2016-11-11 16:02:40] [error] Could not locate a site your user may access identified by barrel-2017.

I encountered the above error when attempting to clone a site.

`terminus site clone --source-site=barrel --target-site=barrel-2017`

```
westurner:SiteClone wes.turner$ terminus site clone --version
+-----------------------------+--------+
| Key                         | Value  |
+-----------------------------+--------+
| Plugin (site clone) Version | 0.1.1  |
| Compatible Terminus Version | 0.13.3 |
+-----------------------------+--------+
westurner:SiteClone wes.turner$ terminus cli info
+-------------------------+------------------------------------------+
| Key                     | Value                                    |
+-------------------------+------------------------------------------+
| PHP binary              | /usr/local/Cellar/php70/7.0.12_5/bin/php |
| PHP version             | 7.0.12                                   |
| php.ini used            | /usr/local/etc/php/7.0/php.ini           |
| Terminus project config | /Volumes/Master/wes.turner/terminus      |
| Terminus Path           | /usr/local/Cellar/terminus/0.13.4        |
| Terminus version        | 0.13.5                                   |
+-------------------------+------------------------------------------+
```

**Comment by bwood** [comment]
@wturnerharris by default the command is going to try to create a new site in the same organization as the source site.  It appears you aren't allowed to create sites in that organization.  So you should do the following:
1. `terminus organizations list` will show you your organizations.
2. `terminus site clone --source-site=barrel --target-site=barrel-2017 --target-site-org=$MY_ORG` where $MY_ORG is the ID (or quoted name) of the org where you want to create the cloned site.

**Comment by wturnerharris** [comment]
Thanks @bwood - I ended up finding and using that `--target-site-org` option, which worked, but my user is affiliated with the same organization from which the source site was cloned. Strange.
